CREATE DATABASE QLLL_CHI_TIEU_CA_NHAN;
GO

USE QLLL_CHI_TIEU_CA_NHAN;
GO

CREATE TABLE TAI_KHOAN (
    ID_TAI_KHOAN INT IDENTITY PRIMARY KEY,
    TEN_DANG_NHAP NVARCHAR(50) UNIQUE NOT NULL,
    MAT_KHAU NVARCHAR(255) NOT NULL,
    HO_TEN NVARCHAR(100) NOT NULL,
    VAI_TRO NVARCHAR(20) NOT NULL DEFAULT 'USER',
    NGAY_TAO DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE DANH_MUC (
    ID_DANH_MUC INT IDENTITY PRIMARY KEY,
    TEN_DANH_MUC NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE LOAI_GIAO_DICH (
    ID_LOAI INT IDENTITY PRIMARY KEY,
    TEN_LOAI NVARCHAR(50) NOT NULL
);
GO

CREATE TABLE GIAO_DICH (
    ID_GIAO_DICH INT IDENTITY PRIMARY KEY,
    ID_TAI_KHOAN INT NOT NULL,
    ID_DANH_MUC INT NOT NULL,
    ID_LOAI INT NOT NULL,
    SO_TIEN BIGINT NOT NULL CHECK (SO_TIEN > 0),
    GHI_CHU NVARCHAR(500),
    THOI_GIAN DATETIME NOT NULL,

    FOREIGN KEY (ID_TAI_KHOAN) REFERENCES TAI_KHOAN(ID_TAI_KHOAN),
    FOREIGN KEY (ID_DANH_MUC) REFERENCES DANH_MUC(ID_DANH_MUC),
    FOREIGN KEY (ID_LOAI) REFERENCES LOAI_GIAO_DICH(ID_LOAI)
);
GO

INSERT INTO TAI_KHOAN (TEN_DANG_NHAP, MAT_KHAU, HO_TEN, VAI_TRO) VALUES
(N'admin', N'YWRtaW4xMjNfc2FsdF8xMg==:y8Ysi0BCCLdLA9VM9IPrMM9+v5eVRrGQhn/S4UkfyFw=', N'Quản trị viên', N'ADMIN'),
(N'user', N'dXNlcjEyM19zYWx0XzEyMw==:7OYqgqYs7DkmHqifCcjVtt8DeB6g/yHIcyS6Sp7cz5U=', N'Người dùng mẫu', N'USER');
GO

INSERT INTO DANH_MUC (TEN_DANH_MUC) VALUES
(N'Mua sắm'),
(N'Ăn uống'),
(N'Đổ xăng'),
(N'Tiền nhà'),
(N'Tiền điện'),
(N'Tiền nước'),
(N'Tiền học'),
(N'Tiền mạng'),
(N'Tiền sửa đồ'),
(N'Xe cộ'),
(N'Làm đẹp'),
(N'Cà phê - Trà sữa'),
(N'Khám chữa bệnh'),
(N'Tiền lương');
GO

INSERT INTO LOAI_GIAO_DICH (TEN_LOAI) VALUES
(N'Chi tiền'),
(N'Thu tiền');
GO

INSERT INTO GIAO_DICH (ID_TAI_KHOAN, ID_DANH_MUC, ID_LOAI, SO_TIEN, GHI_CHU, THOI_GIAN) VALUES
(1, 14, 2, 8000000, N'Lương tháng', GETDATE()),
(1, 2, 1, 50000, N'Ăn trưa', GETDATE()),
(2, 1, 1, 120000, N'Mua đồ cá nhân', GETDATE());
GO
USE QLLL_CHI_TIEU_CA_NHAN;
GO

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES;
USE QLLL_CHI_TIEU_CA_NHAN;
GO

SELECT TEN_DANG_NHAP, HO_TEN, VAI_TRO
FROM TAI_KHOAN;