server.host=localhost
server.port=9000
server.threadPoolSize=10

database.url=jdbc:sqlserver://ASUSF15;instanceName=SQLEXPRESS;databaseName=QLLL_CHI_TIEU_CA_NHAN;encrypt=true;trustServerCertificate=true;
database.user=sa
database.password=Demo@123

security.aesKey=1234567890123456
